export const authStyles = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#e8f5f0',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1rem',
    fontFamily: "'Segoe UI', sans-serif",
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '2.5rem 2rem',
    width: '100%',
    maxWidth: '420px',
    boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '0.25rem',
  },
  logoIcon: {
    backgroundColor: '#2ecc8f',
    borderRadius: '10px',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.2rem',
  },
  logoText: {
    fontSize: '1.5rem',
    fontWeight: '700' as const,
    color: '#1a1a1a',
  },
  title: {
    textAlign: 'center' as const,
    fontSize: '1.25rem',
    fontWeight: '700' as const,
    color: '#1a1a1a',
    marginTop: '0.5rem',
    marginBottom: '0',
  },
  subtitle: {
    textAlign: 'center' as const,
    color: '#888',
    fontSize: '0.9rem',
    marginBottom: '1.75rem',
  },
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '600' as const,
    color: '#333',
    marginBottom: '0.4rem',
  },
  input: {
    width: '100%',
    padding: '0.75rem 1rem',
    borderRadius: '10px',
    border: '1px solid #e0e0e0',
    backgroundColor: '#f7f7f7',
    fontSize: '0.95rem',
    outline: 'none',
    boxSizing: 'border-box' as const,
    marginBottom: '1.25rem',
  },
  button: {
    width: '100%',
    padding: '0.85rem',
    backgroundColor: '#2ecc8f',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '1rem',
    fontWeight: '600' as const,
    cursor: 'pointer',
    marginBottom: '1.25rem',
  },
  buttonDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed' as const,
  },
  link: {
    color: '#2ecc8f',
    fontWeight: '600' as const,
    textDecoration: 'none',
  },
  forgotPassword: {
    display: 'block',
    textAlign: 'right' as const,
    color: '#2ecc8f',
    fontSize: '0.85rem',
    textDecoration: 'none',
    marginTop: '-0.75rem',
    marginBottom: '1.5rem',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    fontSize: '0.875rem',
    color: '#555',
  },
  footer: {
    textAlign: 'center' as const,
    fontSize: '0.875rem',
    color: '#555',
  },
  error: {
    color: '#e74c3c',
    fontSize: '0.85rem',
    marginBottom: '1rem',
    textAlign: 'center' as const,
  },
  copyright: {
    marginTop: '1.5rem',
    color: '#aaa',
    fontSize: '0.8rem',
  },
};